import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import Dice from '../components/Dice'
import BettingTable from '../components/BettingTable'

type BetType = 'pass' | 'dontpass' | 'field' | 'place6' | 'place8'

function Craps() {
  const [dice, setDice] = useState([3, 4]); const [rolling, setRolling] = useState(false); const [phase, setPhase] = useState<'comeout' | 'point'>('comeout'); const [point, setPoint] = useState<number | null>(null); const [balance, setBalance] = useState(1000); const [bet, setBet] = useState<BetType>('pass'); const [amount, setAmount] = useState(25); const [message, setMessage] = useState('Place a wager to begin the come-out roll.'); const audio = useRef<Record<string, HTMLAudioElement>>({})
  const soundBase = `${import.meta.env.BASE_URL}sounds/`
  useEffect(() => { ['dice-roll', 'dice-hit', 'win', 'lose', 'welcome'].forEach((name) => { const sound = new Audio(`${soundBase}${name}.mp3`); sound.preload = 'auto'; audio.current[name] = sound }) }, [soundBase])
  const play = (name: string) => { const sound = audio.current[name]; if (sound) { sound.currentTime = 0; void sound.play().catch(() => undefined) } }
  const roll = () => { if (rolling || balance < amount) return; setRolling(true); play('dice-roll'); setTimeout(() => { const next = [Math.ceil(Math.random() * 6), Math.ceil(Math.random() * 6)]; const total = next[0] + next[1]; setDice(next); play('dice-hit'); let won: boolean | null = null; let text = `Rolled ${total}.`; if (bet === 'field') won = [3, 4, 9, 10, 11].includes(total); else if (bet === 'place6' || bet === 'place8') won = total === Number(bet.slice(-1)); else if (phase === 'comeout') { if ([7, 11].includes(total)) won = bet === 'pass'; else if ([2, 3].includes(total)) won = bet === 'dontpass'; else if (total === 12) won = bet === 'dontpass' ? null : false; else { setPoint(total); setPhase('point'); text = `Point is ${total}. Roll it again before seven.` } } else if (total === point || total === 7) { won = total === point ? bet === 'pass' : bet === 'dontpass'; setPhase('comeout'); setPoint(null); text = total === 7 ? 'Seven out.' : `Point ${total} hit.` } else text = `Rolled ${total}. Point remains ${point}.`; if (won === true) { setBalance((value) => value + amount); play('win'); text += ' You win.' } else if (won === false) { setBalance((value) => value - amount); play('lose'); text += ' Wager lost.' } setMessage(text); setRolling(false) }, 550) }
  return <main className="craps-page page-image" style={{ backgroundImage: `url('${import.meta.env.BASE_URL}images/julian-paefgen-uxU_jyu9e7U-unsplash.jpg')` }}><div className="image-overlay" /><header className="product-nav product-nav-overlay"><Link to="/" className="brand">PERSONAL SYSTEMS</Link><nav><Link className="current" to="/craps">Craps</Link><Link to="/dashboard">Dashboard</Link></nav><span className="status-badge">TABLE 04</span></header><section className="craps-layout-new"><div className="craps-main-new"><div className="table-header"><div><p className="eyebrow">LIVE TABLE / PASS LINE</p><h1>Computerized Craps</h1></div><div className="point-display"><small>POINT</small><strong>{point ?? 'OFF'}</strong></div></div><div className="felt-table" style={{ backgroundColor: 'rgba(6, 19, 16, .72)', backgroundImage: `url('${import.meta.env.BASE_URL}images/dice-on-craps-table-2260559.jpg')`, backgroundBlendMode: 'multiply' }}><div className="roll-status"><span className={rolling ? 'pulse-dot' : 'live-dot'} />{rolling ? 'Rolling dice' : phase === 'point' ? `Point ${point}` : 'Come-out roll'}</div><div className="dice-row"><Dice value={dice[0]} rolling={rolling} /><Dice value={dice[1]} rolling={rolling} /></div><p className={`game-message${message.toLowerCase().includes('win') ? ' win-message' : message.toLowerCase().includes('lost') ? ' lose-message' : ''}`} role="status">{message}</p><button className="roll-button" type="button" onClick={roll} disabled={rolling || balance < amount}>{rolling ? 'Rolling...' : 'Roll dice'} <span>↗</span></button></div><div className="table-metrics"><div><small>Last roll</small><strong>{dice[0]} + {dice[1]} = {dice[0] + dice[1]}</strong></div><div><small>Session</small><strong>Come-out {phase === 'comeout' ? 'active' : 'in play'}</strong></div></div></div><aside className="craps-sidebar-new"><div className="balance-panel"><small>AVAILABLE BALANCE</small><strong>${balance.toLocaleString()}</strong><span className={balance >= 1000 ? 'positive' : 'negative'}>{balance >= 1000 ? '+$0.00' : `-$${(1000 - balance).toFixed(2)}`} session P/L</span></div><BettingTable selectedBet={bet} onSelectBet={(value) => { setBet(value as BetType); play('chip') }} amount={amount} onAmountChange={setAmount} disabled={rolling || phase === 'point'} /></aside></section></main>
}

export default Craps
